package com.qa.opencart.pages;

import org.testng.Assert;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Stores reusable JSON payloads and expected payload values for API tests.
 *
 * <p>The user create/update methods are used by Users_Data_API to send request
 * bodies and then validate the response values against the same generated data.</p>
 */
public class Payload {
    private static String createdUserName;
    private static String createdUserEmail;
    private static String createdUserGender;
    private static String createdUserStatus;
    private static String updatedUserName;
    private static String updatedUserStatus;
    private static final Map<String, Integer> createdUserIds = new ConcurrentHashMap<>();


    /**
     * Returns a sample course/event JSON response used by
     * Users_Data_API.mockResponseCheck() for JsonPath parsing practice.
     *
     * @return sample JSON string containing event data and pagination details
     */
    public static String coursePrice() {
        return "{\n" +
                "  \"success\": true,\n" +
                "  \"data\": [\n" +
                "    {\n" +
                "      \"id\": 1,\n" +
                "      \"title\": \"Tech Summit 2026\",\n" +
                "      \"description\": \"A premier technology conference bringing together industry leaders.\",\n" +
                "      \"category\": \"Conference\",\n" +
                "      \"venue\": \"Bangalore International Centre\",\n" +
                "      \"city\": \"Bangalore\",\n" +
                "      \"eventDate\": \"2026-06-15T09:00:00.000Z\",\n" +
                "      \"price\": 1500,\n" +
                "      \"totalSeats\": 500,\n" +
                "      \"availableSeats\": 342,\n" +
                "      \"imageUrl\": \"https://example.com/images/tech-summit.jpg\",\n" +
                "      \"createdAt\": \"2026-08-13T18:51:45.754Z\",\n" +
                "      \"updatedAt\": \"2026-08-13T18:51:45.754Z\"\n" +
                "    },\n" +
                "\n" +
                "    {\n" +
                "      \"id\": 2,\n" +
                "      \"title\": \"Tech Summit 2027\",\n" +
                "      \"description\": \"A premier technology conference bringing together industry leaders.\",\n" +
                "      \"category\": \"Conference\",\n" +
                "      \"venue\": \"Bangalore International Centre\",\n" +
                "      \"city\": \"Bangalore\",\n" +
                "      \"eventDate\": \"2026-06-15T09:00:00.000Z\",\n" +
                "      \"price\": 1500,\n" +
                "      \"totalSeats\": 500,\n" +
                "      \"availableSeats\": 342,\n" +
                "      \"imageUrl\": \"https://example.com/images/tech-summit.jpg\",\n" +
                "      \"createdAt\": \"2026-08-13T18:51:45.754Z\",\n" +
                "      \"updatedAt\": \"2026-08-13T18:51:45.754Z\"\n" +
                "    }\n" +
                "  ],\n" +
                "  \"pagination\": {\n" +
                "    \"total\": 48,\n" +
                "    \"page\": 1,\n" +
                "    \"limit\": 10,\n" +
                "    \"totalPages\": 5\n" +
                "  }\n" +
                "}\n";
    }

    /**
     * Builds the POST /users request body used by
     * Users_Data_API.createUserApiTest().
     *
     * <p>The generated values are stored in this class so the same expected
     * values can be reused in create, get, update, and get-updated assertions.</p>
     *
     * @return JSON request body for creating a GoRest user
     */
//    public static String userData() {
//        String uniqueValue = String.valueOf(System.currentTimeMillis());
//        createdUserName = "piyush wadhwa " + uniqueValue;
//        createdUserEmail = "piyush" + uniqueValue + "@example.com";
//        createdUserGender = "male";
//        createdUserStatus = "active";
//
//        return userData(createdUserName, createdUserEmail, createdUserGender, createdUserStatus);
//    }
//
    public static String userData(String name, String email, String gender, String status) {
        createdUserName = name;
        createdUserEmail = email;
        createdUserGender = gender;
        createdUserStatus = status;

        return "{ \"name\": \"" + createdUserName + "\", \"email\": \"" + createdUserEmail + "\", \"gender\": \"" + createdUserGender + "\", \"status\": \"" + createdUserStatus + "\" }";
    }

    /**
     * Returns the name generated by userData().
     * Used in Users_Data_API response assertions.
     *
     * @return expected created user name
     */
    public static String getCreatedUserName() {
        return createdUserName;
    }

    /**
     * Returns the email generated by userData().
     * Used in Users_Data_API response assertions.
     *
     * @return expected created user email
     */
    public static String getCreatedUserEmail() {
        return createdUserEmail;
    }

    /**
     * Returns the gender generated by userData().
     * Used in Users_Data_API response assertions.
     *
     * @return expected created user gender
     */
    public static String getCreatedUserGender() {
        return createdUserGender;
    }

    /**
     * Returns the status generated by userData().
     * Used in Users_Data_API response assertions before the user is updated.
     *
     * @return expected created user status
     */
    public static String getCreatedUserStatus() {
        return createdUserStatus;
    }

    /**
     * Builds the PUT /users/{userId} request body used by
     * Users_Data_API.updateUserApiTest().
     *
     * <p>The updated values are stored in this class so they can be reused in
     * update and get-updated assertions.</p>
     *
     * @return JSON request body for updating a GoRest user
     */
    public static String userUpdateData() {
        return userUpdateData("piyush wadhwa updated", "inactive");
    }

    public static String userUpdateData(String name, String status) {
        updatedUserName = name;
        updatedUserStatus = status;

        return "{ \"name\": \"" + updatedUserName + "\", \"status\": \"" + updatedUserStatus + "\" }";
    }

    /**
     * Returns the name generated by userUpdateData().
     * Used in Users_Data_API response assertions after update.
     *
     * @return expected updated user name
     */
    public static String getUpdatedUserName() {
        return updatedUserName;
    }

    /**
     * Returns the status generated by userUpdateData().
     * Used in Users_Data_API response assertions after update.
     *
     * @return expected updated user status
     */
    public static String getUpdatedUserStatus() {
        return updatedUserStatus;
    }
    public static void saveCreatedUserId(String email, Integer userId) {
        createdUserIds.put(email, userId);
    }

    public static Integer getCreatedUserId(String email) {
        Integer userId = createdUserIds.get(email);
        Assert.assertNotNull(userId, "No created user id found for email: " + email);
        return userId;
    }

    public static void removeCreatedUserId(String email) {
        createdUserIds.remove(email);
    }
}
